use_frameworks!

target 'SKInkAnimator_Example' do
  pod 'SKInkAnimator', :path => '../'

  target 'SKInkAnimator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
